// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/get/{short}": {
            "get": {
                "description": "Get original link by short equivalent",
                "produces": [
                    "application/json"
                ],
                "summary": "Get original link by short equivalent",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Short",
                        "name": "short",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.GetResponse"
                        }
                    }
                }
            }
        },
        "/api/make": {
            "post": {
                "description": "Make short link",
                "produces": [
                    "application/json"
                ],
                "summary": "Make short link",
                "parameters": [
                    {
                        "description": "Make request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.MakeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.MakeResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.GetResponse": {
            "type": "object",
            "properties": {
                "original": {
                    "type": "string",
                    "example": "http://example.com/"
                }
            }
        },
        "controllers.MakeRequest": {
            "type": "object",
            "required": [
                "link"
            ],
            "properties": {
                "link": {
                    "type": "string",
                    "maxLength": 1000,
                    "minLength": 2,
                    "example": "http://example.com/da3rsf"
                },
                "short": {
                    "type": "string",
                    "example": "da3rsf"
                }
            }
        },
        "controllers.MakeResponse": {
            "type": "object",
            "properties": {
                "short": {
                    "type": "string",
                    "example": "http://example.com/da3rsf"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Link shortener API",
	Description:      "api for making short links",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
